name: workout_warrior
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  google_nav_bar: ^5.0.6
  http: ^1.1.0
  line_icons: ^2.0.3
  multiselect: ^0.1.0
  page_transition: ^2.0.9
  swipeable_page_route: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
